### ISSUE TITLE
数据库恢复时报错

### ISSUE THREAD

**Issue by bendise** [ToManage/TM-CRM_ERP#18]
` mongorestore -h 127.0.0.1 -d erpdb ./dump/new`
出现错误信息：
`Failed: erpdb.Societe: error creating indexes for erpdb.Societe: createIndex error: The field 'safe' is not valid for an index specification. Specification: { language_override: "language", weights: { Tag: 1, name: 1, rival: 1, segmentation.label: 1, zip: 1 }, textIndexVersion: 2, default_language: "english", background: true, name: "name_text_zip_text_Tag_text_rival_text_segmentation.label_text", safe: null, ns: "erpdb.Societe", key: { _fts: "text", _ftsx: 1 } }`

**Comment by hepr** [comment]
Today only mongodb 3.2 was supported
Next release will be support 3.4
