### ISSUE TITLE
how can i join and contribute?

### ISSUE THREAD

**Issue by jacksolutions** [ToManage/TM-CRM_ERP#21]
i am also a MEAN stack developer, let me know

**Comment by jacksolutions** [comment]
is there any roadmap?

**Comment by jacksolutions** [comment]
please let me know

**Comment by hepr** [comment]
Hi,

yes, it's possible to contribute.
The roadmap wasn't defined today because we are testing some products. 

To contribute :
 - create a fork
 - commit your modifications
 - pull request on the main repository

Have a nice day

Herve

**Comment by jacksolutions** [comment]
okay fine, but if you provide specific details, what needs to develop, i can plan in that direction, at the moment without any roadmap, how we know, what we need to develop?

**Comment by hepr** [comment]
A this time we working on develop branch. We create a new product management (PIM)
We are merging some module.

The next need is to create an install module, that configure and create default database. Are you interesting by this ?

**Comment by jacksolutions** [comment]
how about manufacturing module and ware housing? do we have detailed documentation of how the current software works and workflow?

**Comment by jacksolutions** [comment]
Migration from angular1 to React
=> i think it will be totally rewrite? and we also need to include redux cause react is just a view of MVC and for model and controller we need redux,

**Comment by jacksolutions** [comment]
Thank you for sharing the road map

Add lead module
=> for example this module, do we have a specs on how actually it should work ? etc etc?

**Comment by hepr** [comment]
We will create a chat server for realtim communication.
In a few days we can exchange about it.

**Comment by jacksolutions** [comment]
looking forward to it @hepr
