### ISSUE TITLE
pls update dep

### ISSUE THREAD

**Issue by tqangxl** [ToManage/TM-CRM_ERP#23]
D:\Dev\GitHub\TM-CRM_ERP>npm install
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated mongodb@2.1.18: Please upgrade to 2.2.19 or higher
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> iconv@2.3.0 install D:\Dev\GitHub\TM-CRM_ERP\node_modules\iconv
> node-gyp rebuild

D:\Dev\GitHub\TM-CRM_ERP>bower install
Unable to find a suitable version for angular-bootstrap, please choose one by typing one of the numbers below:
    1) angular-bootstrap#^0.12 which resolved to 0.12.1 and is required by angular-dialog-service#5.2.8
    2) angular-bootstrap#0.13.x which resolved to 0.13.4 and is required by tm-js

Prefix the choice with ! to persist it to bower.json

? Answer 2
bower angular                                  resolution Unsuitable resolution declared for angular: ~1.3.x
Unable to find a suitable version for angular-translate, please choose one by typing one of the numbers below:
    1) angular-translate#2.1.x which resolved to 2.1.0 and is required by tm-js
    2) angular-translate#^2.9.2 which resolved to 2.15.2 and is required by angular-dialog-service#5.3.0

**Comment by hepr** [comment]
Bower in not needed
It's for an old version
