### ISSUE TITLE
i'm loggin but return querry {"success":true}

### ISSUE THREAD

**Issue by cuonglq** [ToManage/TM-CRM_ERP#24]
while i'm import databases at dump:
Failed: test.Societe: error creating indexes for test.Societe: createIndex error: The field 'safe' is not valid for an index specification. Specification: { name: "name_text_zip_text_Tag_text_rival_text_segmentation.label_text", weights: { Tag: 1, name: 1, rival: 1, segmentation.label: 1, zip: 1 }, textIndexVersion: 2, default_language: "english", ns: "test.Societe", safe: null, background: true, language_override: "language", key: { _fts: "text", _ftsx: 1 } }

while i'm run file debug.js 
2017-07-15 13:15:13: F.install('model', 'category') ---> Error: Cannot find module 'mongoose-path-tree/node_modules/stream-worker' Error: Cannot find module 'mongoose-path-tree/node_modules/stream-worker'

**Comment by hepr** [comment]
Which version of nodejs do you use ?

**Comment by webrtcman** [comment]
i'm import databases at the same dump:
Failed: test.Societe: error creating indexes for test.Societe: createIndex error: The field 'safe' is not valid for an index specification. Specification: { name: "name_text_zip_text_Tag_text_rival_text_segmentation.label_text", weights: { Tag: 1, name: 1, rival: 1, segmentation.label: 1, zip: 1 }, textIndexVersion: 2, default_language: "english", ns: "test.Societe", safe: null, background: true, language_override: "language", key: { _fts: "text", _ftsx: 1 } }

my nodejs version is v7.10.0 on window10.
I use admin/admin can not login in system.
Any good suggestions?Thanks.

**Comment by hepr** [comment]
In master banch only node 4 and node 6 work
