### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by badmark** [ToManage/TM-CRM_ERP#29]
Cannot get passed this error even when pointing package.json to NPM for this module.

======= 2017-09-28 18:25:02: F.install('model', 'category') ---> Error: Cannot find module 'mongoose-path-tree/node_modules/stream-worker' Error: Cannot find module 'mongoose-path-tree/node_modules/stream-worker'

**Comment by hepr** [comment]
Hi,

Today TM_ERP is only compatible with nodejs 4.x
We will fix it in few weeks.

**Comment by badmark** [comment]
This is on node 4.X, can you specify a specific version to use as there are about a dozen v4.x NodeJS packages. Really want to give this a go!
