### ISSUE TITLE
login credentials returning 'unknown user'

### ISSUE THREAD

**Issue by Nnanyielugo** [ToManage/TM-CRM_ERP#30]
admin/admin doesn't seem to work.
Help!

**Comment by CharnaceRegis** [comment]
admin/admin*

**Comment by Nnanyielugo** [comment]
Doesn't work.

**Comment by CharnaceRegis** [comment]
show me log on terminal, just when you launch with node debug.js

**Comment by hregis** [comment]
@Nnanyielugo 
you use the develop branch ?

**Comment by Nnanyielugo** [comment]
@CharnaceRegis 

-------------------------> DEBUG PID: 17007 (v2.8.0)
traduction ok !
ToManage modules install...
====================================================
PID         : 17013
Node.js     : v8.6.0
Total.js    : v2.8.0
OS          : linux 4.10.0-35-generic
====================================================
Name        : TM-CRM_ERP
Version     : 0.6.0
Author      : ToManage
Date        : 2017-10-18 16:26:06
Mode        : debug
====================================================

http://0.0.0.0:8000/

Dict is not loaded
End update
You need to install or update database form dump directory

**Comment by Nnanyielugo** [comment]
@hregis 
Yeah, I think?

**Comment by CharnaceRegis** [comment]
no BD installed !!

**Comment by timmy63** [comment]
Same problem for me. Extra informations when I run node debug.js command my mongod server line displays `add index fails, too many indexes for aze.Customers.Version key:{ groups.users: 1 }`

I don't know if it's related.

**Comment by ilyes495** [comment]
Hey,
I have the same problem, but I have mongodb up and running, what should I do?

**Comment by hepr** [comment]
Hi

do you have a mongorestore --db demo dump/install ?
