### ISSUE TITLE
Proper way to override template

### ISSUE THREAD

**Issue by harmonico** [ToManage/TM-CRM_ERP#31]
Hello,

I discover this tool and it's pretty awesome.
I'm looking for the proper way to override template files in order to change pictures, add a custom css in the layout file or add a text block for example.

So what's the proper way to do that in order to not modify core files.

Regards :-)

**Comment by hepr** [comment]
Hi,

I had a new themes directory. Just copy tm directory to your new directory and in your config file juste add default-theme : new-theme

You must do a git pull

Regards
