### ISSUE TITLE
Angular1 to Angular2 ?

### ISSUE THREAD

**Issue by Netoperz** [ToManage/TM-CRM_ERP#32]
I see problems on mobile, the actual code on github is working fine when showing view on laptop, but when you open it on mobile the left menu is not showing, no navigation and in that form it is useless.
Solution would be porting to angular 2, I think it would be more easy to port to angular 2 with adding some react stuff when needed in view than rewriting from scratch in react.

What do you think about that ?

**Comment by hepr** [comment]
Hi,

it was a CSS problem, I'll solve it in few days.
There is no mirgration to angular 2. We prefer use vuejs 2 with webpack.

Thx

Herve
